<a href="https://colab.research.google.com/github/gihAzevedo/SantanderCoders/blob/main/determinante.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Determinante**

In [1]:
import numpy as np

In [3]:
mA = np.array([[1,2], [3,4]])
mA

array([[1, 2],
       [3, 4]])

In [5]:
# Calcula o determinante
np.linalg.det(mA)

-2.0000000000000004

In [6]:
# Criar matriz aleatória de números inteiros
mB = np.random.randint(0, 10, size = (4, 4))
mB

array([[0, 2, 9, 5],
       [5, 8, 7, 7],
       [9, 6, 7, 1],
       [3, 0, 2, 5]])

In [7]:
np.linalg.det(mB)

-2298.0

## **Sistemas Lineares**
Resolva a seguinte equação:

2x + y = 4

x + y = 3

In [11]:
# Montando as matrizes
a = np.array([[2, 1], [1, 1]])
b = np.array([4, 3])

In [12]:
# Precisa da inversa da matriz A
a_inv = np.linalg.inv(a)
a_inv

array([[ 1., -1.],
       [-1.,  2.]])

In [13]:
# Basta multiplicar a Matriz B pela inversa da Matriz A
resulMatriz = np.dot(a_inv, b)
resulMatriz

array([1., 2.])

Resolvendo utilizando o **Solve**

In [14]:
resulMatrizSolve = np.linalg.solve(a, b)
resulMatrizSolve

array([1., 2.])