<a href="https://colab.research.google.com/github/gihAzevedo/SantanderCoders/blob/main/matrizesEspeciais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Matriz Transposta**

In [1]:
import numpy as np

In [2]:
matrizA = np.array([[1, 2, 3], [4, 5, 6]])
matrizA

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
transporA = matrizA.transpose()
print(transporA)
# ou
transporT = matrizA.T
print(transporT)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


## **Matriz Inversa**

######Uma matriz(quadrada e o determinante diferente de Zero) que ao multiplicar pela matriz original ela resulta matriz identidade.
##### A x A-¹ = Matriz Identidade

In [11]:
# Exemplo Matriz
matrizB = np.array([[2, 4], [8, 10]])
matrizB

array([[ 2,  4],
       [ 8, 10]])

In [12]:
# Calcular Determinante da Matriz

np.linalg.det(matrizB)

-11.999999999999995

In [13]:
# Calculando Matriz Inversa
matrizInversa = np.linalg.inv(matrizB)
matrizInversa

array([[-0.83333333,  0.33333333],
       [ 0.66666667, -0.16666667]])

In [14]:
# Calculando Matriz Identidade
matrizIdentidade = np.dot(matrizB, matrizInversa)
matrizIdentidade

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

## **Matriz Identidade**

In [16]:
identidade = np.identity(3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
identidade2 = np.eye(3)
identidade2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])