<a href="https://colab.research.google.com/github/gihAzevedo/SantanderCoders/blob/main/Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
matrizA = np.array([[1, 2], [3, 4]])
matrizB = np.array([[5, 6], [7, 8]])

In [10]:
somaMatriz = matrizA + matrizB
somaMatriz

array([[ 6,  8],
       [10, 12]])

In [12]:
subtracaoMatriz = matrizA - matrizB
subtracaoMatriz

array([[-4, -4],
       [-4, -4]])

In [13]:
multMatriz = np.dot(matrizA, matrizB)
multMatriz

array([[19, 22],
       [43, 50]])

In [14]:

# Exercício 1
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9, 10], [11, 12, 13, 14], [15, 16, 17, 18]])

C = np.dot(A, B)  # ou C = A @ B
print("Matriz C:")
print(C)

# Exercício 2
D = np.array([[1, 2], [3, 4], [5, 6]])
E = np.array([[7, 8], [9, 10]])

F = np.dot(D, E)  # ou F = D @ E
print("\nMatriz F:")
print(F)


Matriz C:
[[ 74  80  86  92]
 [173 188 203 218]]

Matriz F:
[[ 25  28]
 [ 57  64]
 [ 89 100]]
