In [7]:
import numpy as np

In [8]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [12]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [15]:
## Matrizes
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
## Notas de alunos
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
print(lista_de_notas)

notas = np.array(lista_de_notas)
print(notas)

[9.8, 5.6, 7.8, 9.1, 6.5]
[9.8 5.6 7.8 9.1 6.5]


In [18]:
print("Maximo", notas.max())
print("Minimo", notas.min())
print("Media", notas.mean())
print("Desvio Padrão", notas.std())
print("Posicao menor", notas.argmin())

Maximo 9.8
Minimo 5.6
Media 7.76
Desvio Padrão 1.5628179676469045
Posicao menor 1


In [19]:
# Exercicio - Criar um programa que peça ao usuário para digitar 5 notas e realizar alguns calculos
# 1 - Criar uma lista e adicionar os elementos a ela.
# 2 - Transformar a lista em um array.
# 3 - Realizar calculos com a lista de array(Minimo, Máximo, Média e Desvio Padrão)

In [30]:
ex_lista = []
for i in range(5):
    ex_lista.append(float(input(f'Insira a {i+1}º nota: ')))
print(ex_lista)

Insira a 1º nota:  7.5
Insira a 2º nota:  4
Insira a 3º nota:  6.8
Insira a 4º nota:  9
Insira a 5º nota:  4.5


[7.5, 4.0, 6.8, 9.0, 4.5]


In [31]:
notas_array = np.array(ex_lista)
print(notas_array)

[7.5 4.  6.8 9.  4.5]


In [39]:
print("Máximo:", notas_array.max())
print("Minimo:", notas_array.min())
print("Média:", notas_array.mean())
print("Desvio Padrão:", notas_array.std())
print("Posição da Menor Nota:", (notas_array.argmin()+1),'º posição.')

Máximo: 9.0
Minimo: 4.0
Média: 6.36
Desvio Padrão: 1.87040102651811
Posição da Menor Nota: 2 º posição.
